name: Build and Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload Plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: JMusicBot
          path: target/*.jar
